export const DictConstants = {
  SYS_BOOLEAN: 'SYS_BOOLEAN',
  SYS_MENU_TYPE: 'SYS_MENU_TYPE',
  SYS_OPEN_TARGET: 'SYS_OPEN_TARGET',
  SYS_CRYPTOGRAPHIC_STRENGTH: 'SYS_CRYPTOGRAPHIC_STRENGTH',
  SYS_DATA_SCOPE: 'SYS_DATA_SCOPE',
  SYS_GENDER: 'SYS_GENDER',
  SYS_ACCOUNT_STATUS: 'SYS_ACCOUNT_STATUS',
}
